// Here's where the actionTypes go.

// NAVBAR
export const SHOW_MOBILE_NAVIGATION_MENU = "SHOW_MOBILE_NAVIGATION_MENU";
export const HIDE_MOBILE_NAVIGATION_MENU = "HIDE_MOBILE_NAVIGATION_MENU";
export const SHOW_MOBILE_ELLIPSIS_MENU = "SHOW_MOBILE_ELLIPSIS_MENU";
export const HIDE_MOBILE_ELLIPSIS_MENU = "HIDE_MOBILE_ELLIPSIS_MENU";

//MODAL FORM FOR ASK QUESTION
export const SHOW_MODAL_FORM = "SHOW_MODAL_FORM";
export const HIDE_MODAL_FORM = "HIDE_MODAL_FORM";

// PATIENT DASHBOARD NAVBAR
export const PATIENT_SELECTED_NAV = "PATIENT_SELECTED_NAV"

//  CONSULTANT DASHBOARD NAVBAR
export const CONSULTANT_SELECTED_NAV = "CONSULTANT_SELECTED_NAV"

// PATIENT RELATION DATA
export const PATIENT_DATA = "PATIENT_DATA"

// CONSULTANT RELATION DATA
export const CONSULTANT_DATA = "CONSULTANT_DATA"

// REMOVE PERSIST
export const REMOVE_PERSIST = "REMOVE_PERSIST"